package mx.yobibytelabs.rescatapp.util;

import java.util.ArrayList;

import mx.yobibytelabs.rescatapp.R;
import mx.yobibytelabs.rescatapp.objetos.Perro;

/**
 * Created by jagspage2013 on 12/08/14.
 */
public class Rellenador {

    public static void rellenarChicos(ArrayList<Perro> lista){


        lista.add(new Perro("Affenpinscher",6,R.drawable.chico_affenpinscher,1));
        lista.add(new Perro("Australian Terrier",7,R.drawable.chico_australian_terrier,1));
        lista.add(new Perro("Cairn Terrier",8,R.drawable.chico_cairn_terrier,1));
        //lista.add(new Perro("Chihuahueño",9,R.drawable.chico_chihuahueno,1));
        lista.add(new Perro("Griffon Belga",10,R.drawable.chico_griffon_belga,1));
        lista.add(new Perro("Griffon Boulet",11,R.drawable.chico_griffon_boulet,1));
        //lista.add(new Perro("Griffon de Arret",12,R.drawable.chico_griffon_de_arret,1));
        //lista.add(new Perro("Griffon de Brabante",13,R.drawable.chico_griffon_de_brabante,1));
        //lista.add(new Perro("Griffon de Bruselas",14,R.drawable.chico_griffon_de_bruselas,1));
        lista.add(new Perro("Maltés",15,R.drawable.chico_maltes,1));
        //lista.add(new Perro("Manchester Terrier",16,R.drawable.chico_manchester_terrier,1));
        lista.add(new Perro("Norfolk Terrier",17,R.drawable.chico_norfolk_terrier,1));
        //lista.add(new Perro("Norwich Terrier",18,R.drawable.chico_norwich_terrier,1));
        lista.add(new Perro("Papillon",19,R.drawable.chico_papillon,1));
        //lista.add(new Perro("Pastor Polaco de la Llanura",20,R.drawable.chico_pastor_polaco_de_la_llanura,1));
        lista.add(new Perro("Pekinés",21,R.drawable.chico_pekines,1));
        lista.add(new Perro("Pinscher Miniatura",22,R.drawable.chico_pinscher_miniatura,1));
        lista.add(new Perro("Poodle Minitoy",23,R.drawable.chico_poodle_minitoy,1));
        lista.add(new Perro("Scottish Terrier",24,R.drawable.chico_scottish_terrier,1));
        lista.add(new Perro("Sealyham Terrier",25,R.drawable.chico_sealyham_terrier,1));
        lista.add(new Perro("Shih Tzu",26,R.drawable.chico_shih_tzu,1));
        lista.add(new Perro("Silky Terrier",27,R.drawable.chico_silky_terrier,1));
        lista.add(new Perro("Skye Terrier",28,R.drawable.chico_skye_terrier,1));
        //lista.add(new Perro("Spaniel Continental Miniatura",29,R.drawable.chico_spaniel_continental_miniatura,1));
        lista.add(new Perro("Spaniel Tibetano",30,R.drawable.chico_spaniel_tibetano,1));
        lista.add(new Perro("Spitz Alemán Miniatura",31,R.drawable.chico_spitz_aleman_miniatura,1));
        lista.add(new Perro("Spitz Alemán Pomerania",32,R.drawable.chico_spitz_aleman_pomerania,1));
        lista.add(new Perro("Teckels",33,R.drawable.chico_teckels,1));
        lista.add(new Perro("Terrier Escocés",34,R.drawable.chico_terrier_escoces,1));
        lista.add(new Perro("Toy Terrier",35,R.drawable.chico_toy_terrier,1));
        lista.add(new Perro("Yorkshire Terrier",36,R.drawable.chico_yorkshire_terrier,1));
    }

    public static void rellenarMedianos(ArrayList<Perro> lista){
        lista.add(new Perro("Américan Water Spaniel",37,R.drawable.mediano_american_water_spaniel,2));
        lista.add(new Perro("Anglo-Francés de Caza Menor",38,R.drawable.mediano_anglo_frances_de_caza_menor,2));
        lista.add(new Perro("Australian Sheepherd",39,R.drawable.mediano_australian_sheepherd,2));
        lista.add(new Perro("Basenji",40,R.drawable.mediano_basenji,2));
        lista.add(new Perro("Basset Artesiano Normando",41,R.drawable.mediano_basset_artesiano_normando,2));
        lista.add(new Perro("Basset Azul de Gascuña",42,R.drawable.mediano_basset_azul_de_gascuna,2));
        lista.add(new Perro("Basset de Artois",43,R.drawable.mediano_basset_de_artois,2));
        lista.add(new Perro("Basset de los Alpes",44,R.drawable.mediano_basset_de_los_alpes,2));
        lista.add(new Perro("Basset de Westfalia",45,R.drawable.mediano_basset_de_westfalia,2));
        lista.add(new Perro("Basset Hound",46,R.drawable.mediano_basset_hound,2));
        lista.add(new Perro("Basset Leonado de Bretaña",47,R.drawable.mediano_basset_leonado_de_bretana,2));
        lista.add(new Perro("Beagle",48,R.drawable.mediano_beagle,2));
        lista.add(new Perro("Beagle Harrier",49,R.drawable.mediano_beagle_harrier,2));
        //lista.add(new Perro("Bedlington Terrier",50,R.drawable.mediano_bedlington_terrier,2));
        //lista.add(new Perro("Bichón Frisé",51,R.drawable.mediano_bichon_frise,2));
        //lista.add(new Perro("Bichón Habanero",52,R.drawable.mediano_bichon_habanero,2));
        //lista.add(new Perro("Boloñés",53,R.drawable.mediano_bolones,2));
        //lista.add(new Perro("Border Collie",54,R.drawable.mediano_border_collie,2));
        //lista.add(new Perro("Border Terrier",55,R.drawable.mediano_border_terrier,2));
        lista.add(new Perro("Boston Terrier",56,R.drawable.mediano_boston_terrier,2));
        lista.add(new Perro("Bouvier de Entlebucher",57,R.drawable.mediano_bouvier_de_entlebucher,2));
        lista.add(new Perro("Briquet Griffon Vendeen",58,R.drawable.mediano_briquet_griffon_vendeen,2));
        lista.add(new Perro("Bull Terrier Inglés",59,R.drawable.mediano_bull_terrier_ingles,2));
        lista.add(new Perro("Bulldog Francés",60,R.drawable.mediano_bulldog_frances,2));
        lista.add(new Perro("Bulldog Inglés",61,R.drawable.mediano_bulldog_ingles,2));
        lista.add(new Perro("Cavalier King Charles Spaniel",62,R.drawable.mediano_cavalier_king_charles_spaniel,2));
        lista.add(new Perro("Cazador de Alces Noruego Gris",63,R.drawable.mediano_cazador_de_alces_noruego_gris,2));
        //lista.add(new Perro("Cazador de Alces Noruego Negro",64,R.drawable.mediano_cazador_de_alces_noruego_negro,2));
        lista.add(new Perro("Cesky Terrier",65,R.drawable.mediano_cesky_terrier,2));
        lista.add(new Perro("Chin Japonés",66,R.drawable.mediano_chin_japones,2));
        lista.add(new Perro("Chow Chow",67,R.drawable.mediano_chow_chow,2));
        lista.add(new Perro("Cocker Spaniel Americano",68,R.drawable.mediano_cocker_spaniel_americano,2));
        lista.add(new Perro("Cocker Spaniel Inglés",69,R.drawable.mediano_cocker_spaniel_ingles,2));
        lista.add(new Perro("Coton de Tulear",70,R.drawable.mediano_coton_de_tulear,2));
        lista.add(new Perro("Crestado Chino",71,R.drawable.mediano_crestado_chino,2));
        lista.add(new Perro("Dachshunds o teckel",72,R.drawable.mediano_dachshunds_o_teckel,2));
        //lista.add(new Perro("Dálmata",73,R.drawable.mediano_daxlmata,2));
        lista.add(new Perro("Dandie Dinmont Terrier",74,R.drawable.mediano_dandie_dinmont_terrier,2));
        lista.add(new Perro("Drever",75,R.drawable.mediano_drever,2));
        //lista.add(new Perro("Elkhound Negro",76,R.drawable.mediano_elkhound_negro,2));
        //lista.add(new Perro("Elkhound Gris",77,R.drawable.mediano_elkhound_gris,2));
        lista.add(new Perro("Epagneul Azul de Picardie",78,R.drawable.mediano_epagneul_azul_de_picardie,2));
        lista.add(new Perro("Epagneul Breton",79,R.drawable.mediano_epagneul_breton,2));
        lista.add(new Perro("Eurasier",80,R.drawable.mediano_eurasier,2));
        lista.add(new Perro("Field Spaniel",81,R.drawable.mediano_field_spaniel,2));
        lista.add(new Perro("Fox Terrier Pelo de Alambre",82,R.drawable.mediano_fox_terrier_pelo_de_alambre,2));
        lista.add(new Perro("Fox Terrier Pelo Liso",83,R.drawable.mediano_fox_terrier_pelo_liso,2));
        lista.add(new Perro("Galgo Italiano",84,R.drawable.mediano_galgo_italiano,2));
        lista.add(new Perro("Griffon Azul de Gascuña",85,R.drawable.mediano_griffon_azul_de_gascuna,2));
        lista.add(new Perro("Griffon Leonado de Bretaña",86,R.drawable.mediano_griffon_leonado_de_bretana,2));
        lista.add(new Perro("Harrier",87,R.drawable.mediano_harrier,2));
        lista.add(new Perro("Griffon Leonado de Bretaña",88,R.drawable.mediano_griffon_leonado_de_bretana,2));
        lista.add(new Perro("Harrier",89,R.drawable.mediano_harrier,2));
        lista.add(new Perro("Hokkaido",90,R.drawable.mediano_hokkaido,2));
        lista.add(new Perro("Irish Glen of Imaal Terrier",91,R.drawable.mediano_irish_glen_of_imaal_terrier,2));
        lista.add(new Perro("Irish Terrier",92,R.drawable.mediano_irish_terrier,2));
        lista.add(new Perro("Jack Rusell Terrier",93,R.drawable.mediano_jack_rusell_terrier,2));
        lista.add(new Perro("Jagdterrier Alemán",94,R.drawable.mediano_jagdterrier_aleman,2));
        lista.add(new Perro("Kai",95,R.drawable.mediano_kai,2));
        lista.add(new Perro("Kelpie",96,R.drawable.mediano_kelpie,2));
        lista.add(new Perro("Kerry Blue Terrier",97,R.drawable.mediano_kerry_blue_terrier,2));
        lista.add(new Perro("King Charles Spaniel",98,R.drawable.mediano_king_charles_spaniel,2));
        lista.add(new Perro("Kishu",99,R.drawable.mediano_kishu,2));
        lista.add(new Perro("Kronfohrlander",100,R.drawable.mediano_kronfohrlander,2));
        lista.add(new Perro("Laika de Siberia Occidental",101,R.drawable.mediano_laika_de_siberia_occidental,2));
        lista.add(new Perro("Laika de Siberia Oriental",102,R.drawable.mediano_laika_de_siberia_oriental,2));
        lista.add(new Perro("Laika Ruso Europeo",103,R.drawable.mediano_laika_ruso_europeo,2));
        lista.add(new Perro("Lakeland Terrier",104,R.drawable.mediano_lakeland_terrier,2));
        lista.add(new Perro("Lhasa Apso",105,R.drawable.mediano_lhasa_apso,2));
        //lista.add(new Perro("Löwchien",106,R.drawable.mediano_lowchien,2));
        lista.add(new Perro("Lundehund Noruego",107,R.drawable.mediano_lundehund_noruego,2));
        lista.add(new Perro("Mudi",108,R.drawable.mediano_mudi,2));
        lista.add(new Perro("Norwegian Buhund",109,R.drawable.mediano_norwegian_buhund,2));
        //lista.add(new Perro("Pastor Catalán",110,R.drawable.mediano_pastor_catalaxn,2));
        lista.add(new Perro("Pastor Croata",111,R.drawable.mediano_pastor_croata,2));
        lista.add(new Perro("Pastor Holandés",112,R.drawable.mediano_pastor_holandes,2));
        lista.add(new Perro("Pastor de Islandia",113,R.drawable.mediano_pastor_de_islandia,2));
        lista.add(new Perro("Pastor de los Pirineos",114,R.drawable.mediano_pastor_de_los_pirineos,2));
        lista.add(new Perro("Pastor de los Pirineos de cara rasa",115,R.drawable.mediano_pastor_de_los_pirineos_de_cara_rasa,2));
        lista.add(new Perro("Pastor de Shetland",116,R.drawable.mediano_pastor_de_shetland,2));
        lista.add(new Perro("Pastor Ganadero Australiano",117,R.drawable.mediano_pastor_ganadero_australiano,2));
        lista.add(new Perro("Pastor Polaco",118,R.drawable.mediano_pastor_polaco,2));
        lista.add(new Perro("Pastor Polaco de Phodale",119,R.drawable.mediano_pastor_polaco_de_phodale,2));
        lista.add(new Perro("Pequeño Azul de Gascuña",120,R.drawable.mediano_pequeno_azul_de_gascuna,2));
        lista.add(new Perro("Pequeño Basset Griffon Vendeen",121,R.drawable.mediano_pequeno_basset_griffon_vendeen,2));
        lista.add(new Perro("Pequeño Gascon Saintongeois",122,R.drawable.mediano_pequeno_gascon_saintongeois,2));
        lista.add(new Perro("Pequeño Munsterlander",123,R.drawable.mediano_pequeno_munsterlander,2));
        lista.add(new Perro("Pequeños Sabuesos Suizos",124,R.drawable.mediano_pequenos_sabuesos_suizos,2));
        lista.add(new Perro("Perro de Aguas Americano",125,R.drawable.mediano_perro_de_aguas_americano,2));
        lista.add(new Perro("Perro de Aguas Español",126,R.drawable.mediano_perro_de_aguas_espanol,2));
        lista.add(new Perro("Perro de Aguas Frisón",127,R.drawable.mediano_perro_de_aguas_frison,2));
        lista.add(new Perro("Perro de Aguas Irlandés",128,R.drawable.mediano_perro_de_aguas_irlandes,2));
        lista.add(new Perro("Perro de Aguas Portugués",129,R.drawable.mediano_perro_de_aguas_portugues,2));
        lista.add(new Perro("Perro de Aguas Romagna",130,R.drawable.mediano_perro_de_aguas_romagna,2));
        lista.add(new Perro("Perro de Canaan",131,R.drawable.mediano_perro_de_canaan,2));
        //lista.add(new Perro("Pequeño Perro Holandés para la Caza Acuática",132,R.drawable.mediano_pequeno_perro_holandes_para_la_caza_acuaxtica,2));
        lista.add(new Perro("Perdiguero Alemán",133,R.drawable.mediano_perdiguero_aleman,2));
        lista.add(new Perro("Perro Finlandés de Laponia",134,R.drawable.mediano_perro_finlandes_de_laponia,2));
        // lista.add(new Perro("Perro Sin Pelo de Perú Medio",135,R.drawable.mediano_perro_sin_pelo_de_perumedio,2));
        //lista.add(new Perro("Perro Sin Pelo de Perú Pequeño",136,R.drawable.mediano_perro_sin_pelo_de_perupequeno,2));
        //lista.add(new Perro("Pinscher",137,R.drawable.mediano_pinscher,2));
        lista.add(new Perro("Pinscher Austriaco de Pelo Corto",138,R.drawable.mediano_pinscher_austriaco_de_pelo_corto,2));
        lista.add(new Perro("Podenco Portugués Mediano",139,R.drawable.mediano_podenco_portugues_mediano,2));
        lista.add(new Perro("Podenco Portugués Pequeño",140,R.drawable.mediano_podenco_portugues_pequeno,2));
        lista.add(new Perro("Poodle Miniatura",141,R.drawable.mediano_poodle_miniatura,2));
        lista.add(new Perro("Poodle Toy",142,R.drawable.mediano_poodle_toy,2));
        lista.add(new Perro("Pug",143,R.drawable.mediano_pug,2));
        lista.add(new Perro("Puli",144,R.drawable.mediano_puli,2));
        lista.add(new Perro("Pumi",145,R.drawable.mediano_pumi,2));
        lista.add(new Perro("Sabueso Artesiano",146,R.drawable.mediano_sabueso_artesiano,2));
        lista.add(new Perro("Sabueso de Istria Pelo Corto",147,R.drawable.mediano_sabueso_de_istria_pelo_corto,2));
        lista.add(new Perro("Sabueso de Istria Pelo Duro",148,R.drawable.mediano_sabueso_de_istria_pelo_duro,2));
        lista.add(new Perro("Sabueso de Sangre de Baviera",149,R.drawable.mediano_sabueso_de_sangre_de_baviera,2));
        lista.add(new Perro("Sabueso de Halden",150,R.drawable.mediano_sabueso_de_halden,2));
        lista.add(new Perro("Sabueso de Hygen",151,R.drawable.mediano_sabueso_de_hygen,2));
        lista.add(new Perro("Sabueso de Sangre de Hannover",152,R.drawable.mediano_sabueso_de_sangre_de_hannover,2));
        lista.add(new Perro("Sabueso de los Balcanes",153,R.drawable.mediano_sabueso_de_los_balcanes,2));
        lista.add(new Perro("Sabueso Eslovaco",154,R.drawable.mediano_sabueso_eslovaco,2));
        lista.add(new Perro("Sabueso Español",155,R.drawable.mediano_sabueso_espanol,2));
        lista.add(new Perro("Sabueso Helénico",156,R.drawable.mediano_sabueso_helenico,2));
        lista.add(new Perro("Sabueso Noruego",157,R.drawable.mediano_sabueso_noruego,2));
        lista.add(new Perro("Sabueso de Smaland",158,R.drawable.mediano_sabueso_de_smaland,2));
        lista.add(new Perro("Sabuesos Suizos",159,R.drawable.mediano_sabuesos_suizos,2));
        lista.add(new Perro("Sabueso Tirolés",160,R.drawable.mediano_sabueso_tiroles,2));
        lista.add(new Perro("Schapendoes",161,R.drawable.mediano_schapendoes,2));
        lista.add(new Perro("Schipperke",162,R.drawable.mediano_schipperke,2));
        lista.add(new Perro("Smoushond Holandés",163,R.drawable.mediano_smoushond_holandes,2));
        lista.add(new Perro("Spaniel Azul de Picardia",164,R.drawable.mediano_spaniel_azul_de_picardia,2));
        lista.add(new Perro("Schnauzer Estandar",165,R.drawable.mediano_schnauzer_estandar,2));
        lista.add(new Perro("Schnauzer Miniatura",166,R.drawable.mediano_schnauzer_miniatura,2));
        lista.add(new Perro("Setter Ingés",167,R.drawable.mediano_setter_inges,2));
        lista.add(new Perro("Shar Pei",168,R.drawable.mediano_shar_pei,2));
        lista.add(new Perro("Shiba Inu",169,R.drawable.mediano_shiba_inu,2));
        lista.add(new Perro("Shikoku",170,R.drawable.mediano_shikoku,2));
        lista.add(new Perro("Soft Coated Wheaten Terrier",171,R.drawable.mediano_soft_coated_wheaten_terrier,2));
        lista.add(new Perro("Spaniel Bretón",172,R.drawable.mediano_spaniel_breton,2));
        lista.add(new Perro("Spaniel de Campo",173,R.drawable.mediano_spaniel_de_campo,2));
        lista.add(new Perro("Spaniel Francés",174,R.drawable.mediano_spaniel_frances,2));
        lista.add(new Perro("Spaniel Picardo",175,R.drawable.mediano_spaniel_picardo,2));
        lista.add(new Perro("Spaniel Japonés",176,R.drawable.mediano_spaniel_japones,2));
        lista.add(new Perro("Spitz Alemán Grande",177,R.drawable.mediano_spitz_aleman_grande,2));
        lista.add(new Perro("Spitz Alemán Mediano",178,R.drawable.mediano_spitz_aleman_mediano,2));
        lista.add(new Perro("Spitz de Norbotten",179,R.drawable.mediano_spitz_de_norbotten,2));
        lista.add(new Perro("Spitz Finlandés",180,R.drawable.mediano_spitz_finlandes,2));
        lista.add(new Perro("Spitz Japonés",181,R.drawable.mediano_spitz_japones,2));
        lista.add(new Perro("Springer Spaniel Galés",182,R.drawable.mediano_springer_spaniel_gales,2));
        lista.add(new Perro("Stabyhoun",183,R.drawable.mediano_stabyhoun,2));
        lista.add(new Perro("Staffordshire Bull Terrier",184,R.drawable.mediano_staffordshire_bull_terrier,2));
        lista.add(new Perro("Staffordshire Terrier Americano",185,R.drawable.mediano_staffordshire_terrier_americano,2));
        lista.add(new Perro("Sussex Spaniel",186,R.drawable.mediano_sussex_spaniel,2));
        lista.add(new Perro("Terrier Brasileño",187,R.drawable.mediano_terrier_brasileno,2));
        lista.add(new Perro("Terrier Japonés",188,R.drawable.mediano_terrier_japones,2));
        lista.add(new Perro("Terrier Tibetano",189,R.drawable.mediano_terrier_tibetano,2));
        lista.add(new Perro("Tchuvatch Eslovaco",190,R.drawable.mediano_tchuvatch_eslovaco,2));
        lista.add(new Perro("Thai Ridgeback",191,R.drawable.mediano_thai_ridgeback,2));
        lista.add(new Perro("Tsechechischer Terrier",192,R.drawable.mediano_tsechechischer_terrier,2));
        lista.add(new Perro("Volpino Italiano",193,R.drawable.mediano_volpino_italiano,2));
        lista.add(new Perro("Welsh Corgi Cardigan",194,R.drawable.mediano_welsh_corgi_cardigan,2));
        lista.add(new Perro("Welsh Corgi Pembroke",195,R.drawable.mediano_welsh_corgi_pembroke,2));
        lista.add(new Perro("Welsh Terrier",196,R.drawable.mediano_welsh_terrier,2));
        lista.add(new Perro("West Highland White Terrier",197,R.drawable.mediano_west_highland_white_terrier,2));
        lista.add(new Perro("Whippet",198,R.drawable.mediano_whippet,2));
        lista.add(new Perro("Xoloitzcuintle Intermedio",199,R.drawable.mediano_xoloitzcuintle_intermedio,2));
        lista.add(new Perro("Xoloitzcuintle Miniatura",200,R.drawable.mediano_xoloitzcuintle_miniatura,2));
    }
    public static void rellenarGrandes(ArrayList<Perro> lista){

        lista.add(new Perro("Afgano",201, R.drawable.grande_afgano,3));
        lista.add(new Perro("Airedale Terrier",202,R.drawable.grande_airedale_terrier,3));
        lista.add(new Perro("Akita Japonés",203,R.drawable.grande_akita_japones,3));
        lista.add(new Perro("Antiguo Pastor Inglés",204,R.drawable.grande_antiguo_pastor_ingles,3));
        lista.add(new Perro("Antiguo Pointer Danés",205,R.drawable.grande_antiguo_pointer_danes,3));
        lista.add(new Perro("Ariegois",206,R.drawable.grande_ariegois,3));
        lista.add(new Perro("Azawakh",207,R.drawable.grande_azawakh,3));
        lista.add(new Perro("Barbet",208,R.drawable.grande_barbet,3));
        lista.add(new Perro("Beauceron",209,R.drawable.grande_beauceron,3));
        lista.add(new Perro("Bernés de la Montaña",210,R.drawable.grande_bernes_de_la_montana,3));
        lista.add(new Perro("Billy",211,R.drawable.grande_billy,3));
        lista.add(new Perro("Black & Tan Coonhound",212,R.drawable.grande_black_and_tan_coonhound,3));
        lista.add(new Perro("Blood Hound",213,R.drawable.grande_blood_hound,3));
        lista.add(new Perro("Bouvier de Appenzeller",214,R.drawable.grande_bouvier_de_appenzeller,3));
        lista.add(new Perro("Bouvier de Flandres",215,R.drawable.grande_bouvier_de_flandres,3));
        lista.add(new Perro("Bouvier de las Ardenas",216,R.drawable.grande_bouvier_de_las_ardenas,3));
        lista.add(new Perro("Boxer",217,R.drawable.grande_boxer,3));
        lista.add(new Perro("Braco Alemán de Pelo Corto",218,R.drawable.grande_braco_aleman_de_pelo_corto,3));
        lista.add(new Perro("Braco Borbonés",219,R.drawable.grande_braco_borbones,3));
        lista.add(new Perro("Braco de Ariege",220,R.drawable.grande_braco_de_ariege,3));
        lista.add(new Perro("Braco de Auvernia",221,R.drawable.grande_braco_de_auvernia,3));
        lista.add(new Perro("Braco de Burgos",222,R.drawable.grande_braco_de_burgos,3));
        lista.add(new Perro("Braco de Dupuy",223,R.drawable.grande_braco_de_dupuy,3));
        //lista.add(new Perro("Braco de San Germán",224,R.drawable.grande_braco_de_san_germaxn,3));
        lista.add(new Perro("Braco Eslovaco de Pelo Corto",225,R.drawable.grande_braco_eslovaco_de_pelo_corto,3));
        lista.add(new Perro("Braco Estirio de Pelo Duro",226,R.drawable.grande_braco_estirio_de_pelo_duro,3));
        lista.add(new Perro("Braco Francés Blanco y Negro",227,R.drawable.grande_braco_frances_blanco_y_negro,3));
        //lista.add(new Perro("Braco Francés Blanco y Rojo",228,R.drawable.grande_braco_frances_blanco_y_rojo,3));
        lista.add(new Perro("Braco Francés tipo Gascuña Grande",229,R.drawable.grande_braco_frances_tipo_gascuna_grande,3));
        lista.add(new Perro("Braco Francés tipo Pirineos",230,R.drawable.grande_braco_frances_tipo_pirineos,3));
        lista.add(new Perro("Braco Húngaro",231,R.drawable.grande_braco_hungaro,3));
        lista.add(new Perro("Braco Italiano",232,R.drawable.grande_braco_italiano,3));
        // lista.add(new Perro("Braco San Germano",233,R.drawable.grande_braco_san_germano,3));
        lista.add(new Perro("Briard",234,R.drawable.grande_briard,3));
        lista.add(new Perro("Broholmer",235,R.drawable.grande_broholmer,3));
        lista.add(new Perro("Bullmastiff",236,R.drawable.grande_bullmastiff,3));
        lista.add(new Perro("Cane Corso",237,R.drawable.grande_cane_corso,3));
        // lista.add(new Perro("Chart Polski (Lebrel Polaco)",238,R.drawable.grande_chart_polski_lebrel_polaco,3));
        lista.add(new Perro("Cirneco del Letna",239,R.drawable.grande_cirneco_del_letna,3));
        lista.add(new Perro("Clumber Spaniel",240,R.drawable.grande_clumber_spaniel,3));
        //lista.add(new Perro("Cobrador de la Bahía de Chesapeake",241,R.drawable.grande_cobrador_de_la_bahia_de_chesapeake,3));
        lista.add(new Perro("Cobrador de Labrador",242,R.drawable.grande_cobrador_de_labrador,3));
        lista.add(new Perro("Cobrador de Pelo Liso",243,R.drawable.grande_cobrador_de_pelo_liso,3));
        lista.add(new Perro("Cobrador de Pelo Rizado",244,R.drawable.grande_cobrador_de_pelo_rizado,3));
        lista.add(new Perro("Cobrador Dorado",245,R.drawable.grande_cobrador_dorado,3));
        lista.add(new Perro("Collie Barbudo",246,R.drawable.grande_collie_barbudo,3));
        lista.add(new Perro("Collie Pelo Corto",247,R.drawable.grande_collie_pelo_corto,3));
        lista.add(new Perro("Collie Pelo Largo",248,R.drawable.grande_collie_pelo_largo,3));
        lista.add(new Perro("Doberman",249,R.drawable.grande_doberman,3));
        lista.add(new Perro("Dogo Argentino",250,R.drawable.grande_dogo_argentino,3));
        lista.add(new Perro("Dogo de Burdeos",251,R.drawable.grande_dogo_de_burdeos,3));
        lista.add(new Perro("Drahtaar",252,R.drawable.grande_drahtaar,3));
        lista.add(new Perro("Epagneul Francés",253,R.drawable.grande_epagneul_frances,3));
        // lista.add(new Perro("Epagneul Picard",254,R.drawable.grande_epagneul_picard,3));
        lista.add(new Perro("Epagneul de Pond-Audemer",255,R.drawable.grande_epagneul_de_pond_audemer,3));
        lista.add(new Perro("Epagneul a Perdix de Drente",256,R.drawable.grande_epagneul_a_perdix_de_drente,3));
        lista.add(new Perro("Fila Brasileño",257,R.drawable.grande_fila_brasileno,3));
        lista.add(new Perro("Fila de San Miguel",258,R.drawable.grande_fila_de_san_miguel,3));
        lista.add(new Perro("Foxhound Americano",259,R.drawable.grande_foxhound_americano,3));
        lista.add(new Perro("Foxhound Inglés",260,R.drawable.grande_foxhound_ingles,3));
        // lista.add(new Perro("Francés Blanco y Anaranjado",261,R.drawable.grande_frances_blanco_y_anaranjado,3));
        lista.add(new Perro("Francés Blanco y Negro",262,R.drawable.grande_frances_blanco_y_negro,3));
        lista.add(new Perro("Francés Tricolor",263,R.drawable.grande_frances_tricolor,3));
        lista.add(new Perro("Galgo Español",264,R.drawable.grande_galgo_espanol,3));
        lista.add(new Perro("Gammel Dansk Honsehund",265,R.drawable.grande_gammel_dansk_honsehund,3));
        lista.add(new Perro("Gordon Setter",266,R.drawable.grande_gordon_setter,3));
        lista.add(new Perro("Gran Anglo-Francés Blanco y Anaranjado",267,R.drawable.grande_gran_anglo_frances_blanco_y_anaranjado,3));
        lista.add(new Perro("Gran Anglo-Francés Blanco y Negro",268,R.drawable.grande_gran_anglo_frances_blanco_y_negro,3));
        //lista.add(new Perro("Gran Anglo-Francés Tricolor",269,R.drawable.grande_gran_anglo_frances_tricolor,3));
        lista.add(new Perro("Gran Azul de Gascuña",270,R.drawable.grande_gran_azul_de_gascuna,3));
        lista.add(new Perro("Gran Basset Griffon Vendeen",271,R.drawable.grande_gran_basset_griffon_vendeen,3));
        lista.add(new Perro("Gran Boyero Suizo",272,R.drawable.grande_gran_boyero_suizo,3));
        lista.add(new Perro("Gran Gascon Saintogeois",273,R.drawable.grande_gran_gascon_saintogeois,3));
        lista.add(new Perro("Gran Griffon Vendeen",274,R.drawable.grande_gran_griffon_vendeen,3));
        lista.add(new Perro("Gran Munsterlander",275,R.drawable.grande_gran_munsterlander,3));
        lista.add(new Perro("Gran Perro Japonés",276,R.drawable.grande_gran_perro_japones,3));
        lista.add(new Perro("Gran Suizo de la Montaña",277,R.drawable.grande_gran_suizo_de_la_montana,3));
        lista.add(new Perro("Greyhound",278,R.drawable.grande_greyhound,3));
        lista.add(new Perro("Griffon de Pelo Lanoso",279,R.drawable.grande_griffon_de_pelo_lanoso,3));
        lista.add(new Perro("Griffon Nivernés",280,R.drawable.grande_griffon_nivernes,3));
        lista.add(new Perro("Haldenstover",281,R.drawable.grande_haldenstover,3));
        lista.add(new Perro("Hamilton Stovare",282,R.drawable.grande_hamilton_stovare,3));
        lista.add(new Perro("Hollandse smoushound",283,R.drawable.grande_hollandse_smoushound,3));
        lista.add(new Perro("Hovawart",284,R.drawable.grande_hovawart,3));
        lista.add(new Perro("Husky Siberiano",285,R.drawable.grande_husky_siberiano,3));
        lista.add(new Perro("Irish Water Spaniel",286,R.drawable.grande_irish_water_spaniel,3));
        //lista.add(new Perro("Jämhtund",287,R.drawable.grande_jamhtund,3));
        lista.add(new Perro("Magyar Agar",288,R.drawable.grande_magyar_agar,3));
        lista.add(new Perro("Malamute de Alaska",289,R.drawable.grande_malamute_de_alaska,3));
        lista.add(new Perro("Mastín de los Pirineos",290,R.drawable.grande_mastin_de_los_pirineos,3));
        lista.add(new Perro("Mastín Español",291,R.drawable.grande_mastin_espanol,3));
        lista.add(new Perro("Mastín Napolitano",292,R.drawable.grande_mastin_napolitano,3));
        lista.add(new Perro("Nova Scotia Duck Tolling Retriever",293,R.drawable.grande_nova_scotia_duck_tolling_retriever,3));
        lista.add(new Perro("Otterhound",294,R.drawable.grande_otterhound,3));
        lista.add(new Perro("Pastor Alemán",295,R.drawable.grande_pastor_aleman,3));
        lista.add(new Perro("Pastor Australiano",296,R.drawable.grande_pastor_australiano,3));
        lista.add(new Perro("Pastor Belga Groenendal",297,R.drawable.grande_pastor_belga_groenendal,3));
        lista.add(new Perro("Pastor Belga Laekenois",298,R.drawable.grande_pastor_belga_laekenois,3));
        lista.add(new Perro("Pastor Belga Malinois",299,R.drawable.grande_pastor_belga_malinois,3));
        lista.add(new Perro("Pastor Belga Terviuren",300,R.drawable.grande_pastor_belga_terviuren,3));
        lista.add(new Perro("Pastor Blanco Suizo",301,R.drawable.grande_pastor_blanco_suizo,3));
        lista.add(new Perro("Pastor de Asia Central",302,R.drawable.grande_pastor_de_asia_central,3));
        lista.add(new Perro("Pastor de Atlas",303,R.drawable.grande_pastor_de_atlas,3));
        lista.add(new Perro("Pastor de Bergamasco",304,R.drawable.grande_pastor_de_bergamasco,3));
        lista.add(new Perro("Pastor de Brie",305,R.drawable.grande_pastor_de_brie,3));
        lista.add(new Perro("Pastor de la Sierra Estrella",306,R.drawable.grande_pastor_de_la_sierra_estrella,3));
        lista.add(new Perro("Pastor de Maremma",307,R.drawable.grande_pastor_de_maremma,3));
        lista.add(new Perro("Pastor de Picardie",308,R.drawable.grande_pastor_de_picardie,3));
        lista.add(new Perro("Pastor de Rusia Meridional",309,R.drawable.grande_pastor_de_rusia_meridional,3));
        lista.add(new Perro("Pastor del Caucaso",310,R.drawable.grande_pastor_del_caucaso,3));
        lista.add(new Perro("Pastor Finlandes de Laponia",311,R.drawable.grande_pastor_finlandes_de_laponia,3));
        lista.add(new Perro("Pastor Holandés",312,R.drawable.grande_pastor_holandes,3));
        lista.add(new Perro("Pastor Mallorquín",313,R.drawable.grande_pastor_mallorquin,3));
        lista.add(new Perro("Pastor Noruego",314,R.drawable.grande_pastor_noruego,3));
        lista.add(new Perro("Pastor Portugues de la Sierra de Aires",315,R.drawable.grande_pastor_portugues_de_la_sierra_de_aires,3));
        lista.add(new Perro("Pastor Sueco de Laponia",316,R.drawable.grande_pastor_sueco_de_laponia,3));
        lista.add(new Perro("Perdiguero de Burgos",317,R.drawable.grande_perdiguero_de_burgos,3));
        lista.add(new Perro("Perdiguero de Drente",318,R.drawable.grande_perdiguero_de_drente,3));
        //lista.add(new Perro("Perdiguero Portugués",319,R.drawable.grande_perdiguero_portugues,3));
        lista.add(new Perro("Perro de Aguas Portugués",320,R.drawable.grande_perro_de_aguas_portugues,3));
        lista.add(new Perro("Perro de Artois",321,R.drawable.grande_perro_de_artois,3));
        lista.add(new Perro("Perro de Castro Laboreiro",322,R.drawable.grande_perro_de_castro_laboreiro,3));
        lista.add(new Perro("Perro de Goenlandia",323,R.drawable.grande_perro_de_goenlandia,3));
        lista.add(new Perro("Perro de los Visigodos",324,R.drawable.grande_perro_de_los_visigodos,3));
        lista.add(new Perro("Perro de Oysel",325,R.drawable.grande_perro_de_oysel,3));
        lista.add(new Perro("Perro de Presa Mallorquín",326,R.drawable.grande_perro_de_presa_mallorquin,3));
        lista.add(new Perro("Perro Lobo Checoslovaco",327,R.drawable.grande_perro_lobo_checoslovaco,3));
        lista.add(new Perro("Perro Lobero de Saarlos",328,R.drawable.grande_perro_lobero_de_saarlos,3));
        lista.add(new Perro("Perro de Los Faraones",329,R.drawable.grande_perro_de_los_faraones,3));
        lista.add(new Perro("Perro de Osos de Carelia",330,R.drawable.grande_perro_de_osos_de_carelia,3));
        lista.add(new Perro("Perro de Presa Canario",331,R.drawable.grande_perro_de_presa_canario,3));
        lista.add(new Perro("Perro Finlandés de Laponia",332,R.drawable.grande_perro_finlandes_de_laponia,3));
        // lista.add(new Perro("Perro Sin Pelo de Perú Grande",333,R.drawable.grande_perro_sin_pelo_de_perugrande,3));
        lista.add(new Perro("Podenco Canario",334,R.drawable.grande_podenco_canario,3));
        lista.add(new Perro("Podenco Ibicenco",335,R.drawable.grande_podenco_ibicenco,3));
        lista.add(new Perro("Podenco Portugués Grande",336,R.drawable.grande_podenco_portugues_grande,3));
        lista.add(new Perro("Pointer Alemán de Pelo Corto",337,R.drawable.grande_pointer_aleman_de_pelo_corto,3));
        lista.add(new Perro("Pointer Alemán de Pelo Duro",338,R.drawable.grande_pointer_aleman_de_pelo_duro,3));
        lista.add(new Perro("Pointer Alemán de Pelo Largo",339,R.drawable.grande_pointer_aleman_de_pelo_largo,3));
        lista.add(new Perro("Pointer Inglés",340,R.drawable.grande_pointer_ingles,3));
        lista.add(new Perro("Poitevin",341,R.drawable.grande_poitevin,3));
        lista.add(new Perro("Poodle Estandar",342,R.drawable.grande_poodle_estandar,3));
        lista.add(new Perro("Porcelana",343,R.drawable.grande_porcelana,3));
        lista.add(new Perro("Presa Canario",344,R.drawable.grande_presa_canario,3));
        //lista.add(new Perro("Pudelpointer",345,R.drawable.grande_pudelpointer,3));
        lista.add(new Perro("Rafeiro de Alentejo",346,R.drawable.grande_rafeiro_de_alentejo,3));
        lista.add(new Perro("Rhodesiano",347,R.drawable.grande_rhodesiano,3));
        lista.add(new Perro("Rottweiler",348,R.drawable.grande_rottweiler,3));
        lista.add(new Perro("Sabueso Alemán",349,R.drawable.grande_sabueso_aleman,3));
        lista.add(new Perro("Sabueso Austriaco Negro y Fuego",350,R.drawable.grande_sabueso_austriaco_negro_y_fuego,3));
        lista.add(new Perro("Sabueso de Bosnia Pelo Duro",351,R.drawable.grande_sabueso_de_bosnia_pelo_duro,3));
        lista.add(new Perro("Sabueso de Hamilton",352,R.drawable.grande_sabueso_de_hamilton,3));
        lista.add(new Perro("Sabueso de Istria Pelo Corto",353,R.drawable.grande_sabueso_de_istria_pelo_corto,3));
        lista.add(new Perro("Sabueso de Posavatz",354,R.drawable.grande_sabueso_de_posavatz,3));
        lista.add(new Perro("Sabueso de Schiller",355,R.drawable.grande_sabueso_de_schiller,3));
        lista.add(new Perro("Sabueso de Transilvania",356,R.drawable.grande_sabueso_de_transilvania,3));
        lista.add(new Perro("Sabueso Finlandés",357,R.drawable.grande_sabueso_finlandes,3));
        lista.add(new Perro("Sabueso Polaco",358,R.drawable.grande_sabueso_polaco,3));
        lista.add(new Perro("Sabueso Tricolor Yugoslavo",359,R.drawable.grande_sabueso_tricolor_yugoslavo,3));
        lista.add(new Perro("Sabueso Yugoslavo de la Montaña",360,R.drawable.grande_sabueso_yugoslavo_de_la_montana,3));
        lista.add(new Perro("Saluki",361,R.drawable.grande_saluki,3));
        lista.add(new Perro("Samoyedo",362,R.drawable.grande_samoyedo,3));
        lista.add(new Perro("San Bernardo",363,R.drawable.grande_san_bernardo,3));
        lista.add(new Perro("Sarplaninac",364,R.drawable.grande_sarplaninac,3));
        lista.add(new Perro("Schnauzer Gigante",365,R.drawable.grande_schnauzer_gigante,3));
        lista.add(new Perro("Segugio Italiano",366,R.drawable.grande_segugio_italiano,3));
        lista.add(new Perro("Setter Gordon",367,R.drawable.grande_setter_gordon,3));
        lista.add(new Perro("Setter Irlandés Rojo",368,R.drawable.grande_setter_irlandes_rojo,3));
        lista.add(new Perro("Setter Irlandés Rojo y Blanco",369,R.drawable.grande_setter_irlandes_rojo_y_blanco,3));
        lista.add(new Perro("Sloughi",370,R.drawable.grande_sloughi,3));
        lista.add(new Perro("Spaniel de Pont Audemer",371,R.drawable.grande_spaniel_de_pont_audemer,3));
        lista.add(new Perro("Spinone Italiano",372,R.drawable.grande_spinone_italiano,3));
        lista.add(new Perro("Spitz Alemán Keeshond",373,R.drawable.grande_spitz_aleman_keeshond,3));
        lista.add(new Perro("Springer Spaniel Inglés",374,R.drawable.grande_springer_spaniel_ingles,3));
        lista.add(new Perro("Stichethaar",375,R.drawable.grande_stichethaar,3));
        lista.add(new Perro("Terranova",376,R.drawable.grande_terranova,3));
        lista.add(new Perro("Terrier Ruso Negro",377,R.drawable.grande_terrier_ruso_negro,3));
        lista.add(new Perro("Tosa",378,R.drawable.grande_tosa,3));
        lista.add(new Perro("Viszla de Pelo Corto",379,R.drawable.grande_viszla_de_pelo_corto,3));
        lista.add(new Perro("Viszla de Pelo Duro",380,R.drawable.grande_viszla_de_pelo_duro,3));
        lista.add(new Perro("Vorstehund pelo Largo",381,R.drawable.grande_vorstehund_pelo_largo,3));
        lista.add(new Perro("Watterhoun",382,R.drawable.grande_watterhoun,3));
        lista.add(new Perro("Weimaraner",383,R.drawable.grande_weimaraner,3));
        lista.add(new Perro("Wire Hair Pointing Griffon",384,R.drawable.grande_wire_hair_pointing_griffon,3));
        //lista.add(new Perro("Xoloitzcuintle Estándar",385,R.drawable.grande_xoloitzcuintle_estaxndar,3));
    }
    public static void rellenarGigantes(ArrayList<Perro> lista){

        lista.add(new Perro("Borzoi",386,R.drawable.gigante_borzoi,4));
        lista.add(new Perro("Deerhound",387,R.drawable.gigante_deerhound,4));
        //lista.add(new Perro("Gigante de los Pirineos",388,R.drawable.gigante_gigante_de_los_pirineos,4));
        lista.add(new Perro("Gran Danés",389,R.drawable.gigante_gran_danes,4));
        lista.add(new Perro("Irish Wolfhound",390,R.drawable.gigante_irish_wolfhound,4));
        //lista.add(new Perro("Komondor",391,R.drawable.gigante_komondor,4));
        lista.add(new Perro("Kuvasz",392,R.drawable.gigante_kuvasz,4));
        lista.add(new Perro("Landseer",393,R.drawable.gigante_landseer,4));
        lista.add(new Perro("Leonberger",394,R.drawable.gigante_leonberger,4));
        //lista.add(new Perro("Lobero de Saarlos",395,R.drawable.gigante_lobero_de_saarlos,4));
        lista.add(new Perro("Mastín Inglés",396,R.drawable.gigante_mastin_ingles,4));
        lista.add(new Perro("Mastín Tibetano",397,R.drawable.gigante_mastin_tibetano,4));
        //lista.add(new Perro("Pastor de Anatolia",398,R.drawable.gigante_pastor_de_anatolia,4));

    }
}
